### PR TITLE
Adding temperature conversions, plus bugfixing the calculations to support it

### PR DESCRIPTION
**Pull request by Spudley**
Added temperature conversions.

- Support for Celsius, Fahrenheit, Kelvin, Rankine and Rømer scales.
- Comprehensive unit tests.
- Fixed bugs in HasFactor and HasRelativeFactor relating to the addition part of the calculation.

### CODE REVIEW

**Comment by pimlie** [comment]
Thanks for the PR, looks great. But isnt the correct spelling `Fahrenheit`? https://en.wikipedia.org/wiki/Fahrenheit

The bugfix/change with regards to the calculation is ok for now, but thinking about it the issue will remain that we would probably want to support both `(x + a) * b` as `(x * a) + b`.

**Comment by Spudley** [comment]
Hi.

Re Fahrenheit -- oh, yes it is. D'oh. I'll correct that when I have a moment tomorrow. (I guess I was having a bad spelling day today; I had an even worse spelling for it in my first commit)

Re the change to the calculator -- you probably don't *need* to support both `(x + a) * b` and `(x * a) + b`, but I can see it could be useful. You'd need a separate change for that though. (it's definitely out of scope for this change as I'd need to write unit tests for it, which would mean I'd also want to have some unit types that use the feature that I can test against).

Once the dust has settled from this PR, I could take a look at doing that change for you, if you like.

**Comment by Spudley** [comment]
Hi. Okay, I've fixed the spelling properly this time. :blush:

**Comment by pimlie** [comment]
Thanks :smile: 

I have no idea which unit would need the other calculation method, so for me its ok to leave it out for now and look at it when that unit comes along. The implementation would be quite easy anyway, just add a third variable so we can do `(x + a) * b + c` I guess. Probably renaming `$ADDITION` to `$ADDITION_BEFORE` and adding `$ADDITION_AFTER` would be best?

**Comment by Spudley** [comment]
Hi. Yes, that's exactly the solution I would go with if you wanted to offer either option.

It's not strictly necessary because if the addition values are hard-coded, then you could hard code the value on either side of the equation.

For example, F -> C calculation is  `C = (F - 32) / 1.8` but if you want to move the addition to the other side, you just need to divide 32 by 1.8, so you could also have `C = (F / 1.8) - 17.778`.

The above doesn't quite come out exact due to rounding errors, but you get the idea; any similar calculation could be done with the addition value on either side, so it isn't necessary to have both.

The reason why you might want to allow both is for cases where it's a cleaner figure or a more recognisable figure on one side than the other. The above example is a good case for that; we all know that the 0°C is 32°F, so it's more comfortable to have 32 in the equation than 17.778. If some other calculation requires the familiar figure to be on the other side, then it would make sense for it to use `ADDITION_AFTER`.

But as I said, I don't know of any conversion type that would require it, so maybe best to leave it for now.

**Pull request merged**
