### PR TITLE
Allow to add multiple single files to the same unit-type

### LINKED ISSUE #15: It's not possible to add multiple single file units to the same unit-type
Right now it's not possible to add multiple single file units to the same unittype.

```php
UnitMap::add('Unit1.php', '\\MyUnits', Length::class);
UnitMap::add('Unit2.php', '\\MyUnits', Length::class);
```

The problem is
https://github.com/pimlie/php-unit-conversion/blob/a12cdb37e09bef998a8991d81da84a0c70381560/src/Map.php#L101

Instead of `$array + $array` it should use `array_merge_recursive()`. This will merge the arrays on the level they should get merged - the array of units in the unit-type.

### PR DESCRIPTION
**Pull request by Gummibeer**
fixes #15

### CODE REVIEW

**Review by pimlie — COMMENTED** [review]
Not sure why Travis doesnt add the checks in the PR, but it seems the tests are failing: https://travis-ci.org/pimlie/php-unit-conversion/jobs/653006962

**Comment by Gummibeer** [comment]
@pimlie the problem aren't the failing tests, they pass - but the shared static `\PhpUnitConversion\Map::$paths` which is manipulated in `\PhpUnitConversionTest\UnitTest::testMultipleCustomUnits`.
That's why all following tests fail.

It's fixed in https://github.com/pimlie/php-unit-conversion/pull/16/commits/1ff17a5d109374024b53c94023c907f366f332c2

**Comment by Gummibeer** [comment]
Hey @pimlie could your review this again?
This change is blocking for us. :(

**Comment by pimlie** [comment]
Sorry for the delay, should be available in v1.2.3

**Comment by Gummibeer** [comment]
Thanks! :)

**Pull request merged**
