### PR TITLE
Added a test that compares every unit against each other

### PR DESCRIPTION
**Pull request by JoshuaBehrens**
I extracted the type management and made a bit more public. This might has to get some more refactoring depending on the further interests and motivations.
This made it possible to have a test that automatically tests every unit against each other to ensure every use case.

### CODE REVIEW

**Comment by pimlie** [comment]
Could you please resolve the conflict due to the merge of the other pr? Looks really good btw!

**Comment by JoshuaBehrens** [comment]
Done

**Comment by JoshuaBehrens** [comment]
Apparently too many test cases to test all the conversion. I did not have those as I ran them through phpstorm. When I execute them via `composer test` then I have the timeout too.

**Comment by JoshuaBehrens** [comment]
Didnt meant to break the php 5.6 travis. How do we approach this?

**Comment by pimlie** [comment]
I was reviewing this and meanwhile realised that it would probably be better to create all the maps in a build step just before publishing? Because once we publish this library the (default) maps are always the same anyway, so no need to look them up dynamically every time you use this library. Also it would probably be better to change the symbol/label stuff to static props as well as its not that they change depending on a value.

With regards to the failing test, I think I would differentiate between `integration` tests (current tests) and `unit` tests (the ones you added here). The distinction is not perfectly true but close enough. Then we run the integration tests on all php versions but the unit tests from this PR only on the latest php version (7.2 atm).

What do you think? If you agree I can merge this and then implement the above myself. Or if you would like to give a go at this thats ok with me too :)

**Comment by JoshuaBehrens** [comment]
If there is an automated way to generate the static data I am fine with that one. But that should be in a good automated way so it never becomes outdated. Otherwise it is able to fail on an update. I am looking forward to a solution that opens the type registry so everyone can add their own units if they need to. But this is contrary to your approach of having a compiled form of these maps.
Yeah a split up of unit and integration test would be nice but I do not think that it is possible yet as the e.g. the parsing is part of your unit base class. The separation is not perfect yet I would say. Although it is a good approach the issue with php 5.6.

**Comment by pimlie** [comment]
I would appreciate your feedback on my latest changes, you should be able to add custom units now. I didnt implement the serialized stuff yet, think about it a bit more it's probably be better to implement a runtime cache for that. But first see if there is a real performance issue...

**Comment by JoshuaBehrens** [comment]
I just had a look on it and I really like the split up of the type registry and mapping. That tidied up the Unit class. In addition I like to enforce code style on the tests. Nothing I can rant about on first sight.

And be sure: I will PR it away :grin:

**Pull request merged**
