### PR TITLE
Ensuring Unit format() doesn't ignore $addSymbol

### PR DESCRIPTION
**Pull request by neilcrookes**

### CODE REVIEW

**Comment by neilcrookes** [comment]
Hi,
Any chance you could merge this bug fix PR please? You're currently ignoring the $addSymbol param in the `Unit::format($precision, $addSymbol)` method, so even if I pass false, the symbol is including in the return value.
Many thanks,
Neil

**Comment by pimlie** [comment]
Sure, but could you please check the CI as it complains about some CS errors?

**Comment by neilcrookes** [comment]
Oops, trailing spaces removed. Thanks

**Comment by pimlie** [comment]
Thanks for the quick fix, great work!

Should be available in `v1.2.1`

**Pull request merged**
